=== AlphinK/Railway-Managment-System/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="company">
<xs:complexType>
<xs:sequence>
<xs:element name="Faculty" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="id" type="xs:integer"></xs:element>
<xs:element name="name" type="xs:string"></xs:element>
<xs:element name="age" type="xs:intger"></xs:element>
<xs:element name="salary" type="MySal"></xs:element>
<xs:element name="email" type="xs:string"></xs:element>
<xs:element name="mobile" type="xs:integer"></xs:element>
<xs:element name="designation" type="xs:string"></xs:element>
<xs:element name="promotion" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="salary">
<xs:restriction base="xs:integer">
<xs:minInclusive value="50000"></xs:minInclusive>
<xs:maxInclusive value="200000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== AlphinK/Railway-Managment-System/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="employee.xsd">
    <employee id="101">
        <id>101</id>
        <name>Krishna Bansal</name>
        <age>21</age>
        <salary>50000</salary>
        <email>krishna.bansal@mca.christuniversity.in</email>
        <mobile>992465209</mobile>
        <designation>Tester</designation>
        <promotion>Developer</promotion>
    </employee>
    <employee id="102">
        <id>102</id>
        <name>Gyan Gartia</name>
        <age>20</age>
        <salary>55000</salary>
        <email>gyan.gartia@mca.christuniversity.in</email>
        <mobile>8856841325</mobile>
        <designation>Tester</designation>
        <promotion>Developer</promotion>
    </employee>
    <employee id="103">
        <id>103</id>
        <name>Pankaj Sharma</name>
        <age>25</age>
        <salary>50000</salary>
        <email>pankaj.sharma@mca.christuniversity.in</email>
        <mobile>992529009</mobile>
        <designation>Junior Developer</designation>
        <promotion>Developer</promotion>
    </employee>
    <employee id="104">
        <id>104</id>
        <name>Prabhu Sir</name>
        <age>42</age>
        <salary>70000</salary>
        <email>prabhu@mca.christuniversity.in</email>
        <mobile>7777777777</mobile>
        <designation>Developer</designation>
        <promotion>Team Leader</promotion>
    </employee>
    <employee id="105">
        <id>105</id>
        <name>Manjunath sir</name>
        <age>44</age>
        <salary>70000</salary>
        <email>manjunath@mca.christuniversity.in</email>
        <mobile>8888888888</mobile>
        <designation>Developer</designation>
        <promotion>Team Leader</promotion>
    </employee>
    <employee id="106">
        <id>106</id>
        <name>JP sir</name>
        <age>55</age>
        <salary>200000</salary>
        <email>jp@mca.christuniversity.in</email>
        <mobile>9999999999</mobile>
        <designation>Team Leader</designation>
        <promotion>Associate Project Manager</promotion>
    </employee>
    <employee id="107">
        <id>107</id>
        <name>Akshay Singhal</name>
        <age>43</age>
        <salary>150000</salary>
        <email>akshay.singhal@mca.christuniversity.in</email>
        <mobile>2222222222</mobile>
        <designation>Developer assistant</designation>
        <promotion>Team Leader</promotion>
    </employee>
    <employee id="108">
        <id>108</id>
        <name>Aditya Biswal</name>
        <age>24</age>
        <salary>70000</salary>
        <email>aditya.biswal@mca.christuniversity.in</email>
        <mobile>7038131072</mobile>
        <designation>Tester</designation>
        <promotion>Developer</promotion>
    </employee>
    <employee id ="109">
        <id>109</id>
        <name>Jeetank Naidu</name>
        <age>22</age>
        <salary>60000</salary>
        <email>jeetank.naidu@mca.christunivesity.in</email>
        <mobile>666666666</mobile>
        <designation>Tester</designation>
        <promotion>Developer</promotion>
    </employee>
    <employee id = "110">
        <id>110</id>
        <name>Priyanka Yadav</name>
        <age>24</age>
        <salary>70000</salary>
        <email>priyanka.yadav@mca.christuniversity.in</email>
        <mobile>6565656565</mobile>
        <designation>Tester</designation>
        <promotion>Developer</promotion>
    </employee>
</company>
